### ISSUE TITLE
Schedule - Text hard to read due to color

### ISSUE THREAD

**Issue by jawadmn** [mhacks/MHacks-Android#5]
We should change the text color on all events in the primary Schedule calendar view to white rather than black- white is easy to ready across all the event background colors (except maybe white). Will need a bit of testing, but black is particularly hard to read on the dark blue background (with dark green a bit hard due to lack in contrast but not too bad).

Another solution would be to brighten up the background colors.

**Comment by boztalay** [comment]
Fixed in e1eeb6e3c540629a3c7db46254df9acd12b0f8f7
