### ISSUE TITLE
Awards - All boxes noticeably switch colors after opening page

### ISSUE THREAD

**Issue by jawadmn** [mhacks/MHacks-Android#6]
How to recreate: Go to the Awards page once, so the data has been loaded before. Then navigate to another page and back. After a moment (once the data is refreshed), many blocks will change colors.

Possible solution: Make a distinct way for how the boxes are colored. Eg, first one is always yellow, then red, then etc. This way, after refreshing the data and the list is recreated, the colors won't be changed due to the background being completely random.

**Comment by boztalay** [comment]
Fixed in c0c5f65e51e0760ccd8469975d2211cdc273327a
